### ISSUE TITLE
Cannot move 'maps_temp' to 'indirect_delta.maps': Permission denied

### ISSUE THREAD

**Issue by HieronZhang** [dgist-datalab/trace_generator#1]
When I'm running the ./test_synthetic.sh, the cmd keeps printing out:
```
mv: cannot move 'maps_temp' to 'indirect_delta.maps': Permission denied
cp: cannot create regular file 'maps_temp': Permission denied
```

even I'm running this script using sudo.
Can you help me solve this issue?

**Comment by jwya2149** [comment]
I'm sorry for the inconvenience. 
The issue seems to be caused by a permission issue when `run_script/run_script.sh` tries to copy `/proc/[pid]/maps` into the current directory. Putting sudo on those lines will solve this issue, but instead I removed the code block that makes this issue because there is no part of this tool that uses `maps` file.

I revised and updated this repository. Please git pull your local files. The latest commit removes some deprecated parts from some bash and python scripts.

**Comment by HieronZhang** [comment]
Thanks!
After I pulled the updates. It worked for the "true_random" workload. But for the "indirect_delta" one, it seems that your script cannot correctly wait for the process (valgrind).

The output shows:
```
Run /mnt/d/CXL-Flash-Tools/trace_generator/test/Synthetic_Workload/indirect_delta with valgrind..
process pid: 2491
/mnt/d/CXL-Flash-Tools/trace_generator/run_script/run_script.sh: line 82: wait: pid 2491 is not a child of this shell
runtime: 0 (sec)
Process end
```

But I used `htop` and found that the process 2491 (valgrind) is still running.

**Comment by jwya2149** [comment]
I don't know the exact cause because the error didn't occur in my system. I think `run_script.sh` found the wrong pid of the newly executed process. 
This tool runs the target program in the background via Valgrind and waits for the process to end. So when you cancel a previous test with Ctrl-C, the valgrind process may still be alive in the background (You can remove old Valgrind process with `sudo pkill -f valgrind`). Or maybe the script found the wrong target pid when your were trying to run multiple tests simultaneously.

I changed the code that sets the target pid of the wait. 
Now it doesn't look for the target pid from the name of the process, it looks for the process pid that the script ran in the background just before. It also checks that the process name of the pid matches the name of the test program.
```
#target_pid=$(ps | grep callgrind | tail -n1 | awk '{print $1}')
target_pid=$!
...
wait $target_pid
```
Note that this tool can run multiple tests simultaneously for virtual memory trace, but only one test at a time for physical memory trace.
I'm sorry for the inconvenience. Let me know again if the issue is not solved.
