### ISSUE TITLE
Questions on implementation details

### ISSUE THREAD

**Issue by Michael-J-K94** [dgist-datalab/trace_generator#5]
Hi! I really enjoyed reading your work (Overcoming the Memory Wall with CXL-Enabled SSDs) and was also impressed by the trace generation tool. Quick questions:

1. Is there any way for the user process to access its current pagemap? If so, why is the kernel module necessary? If not, it does make sense to use the kernel module. (Is it blocked, requiring CAP_SYS_ADMIN ?)
2. Is there a reason for choosing Valgrind, instead of say, Intel Pin tool? Also, I only have experience with the Intel Pin tool; is there any limitations of the Valgrind?

It would be very much appreciated to get any answers.
Thank you.

**Comment by jwya2149** [comment]
Hi! Thank you for your interest in our tool. 

1. The user process can read `/proc/<pid>/pagemap` to obtain Virtual-to-Physical (V2P) information of the current pagemap. However, we made a simple kernel module that do not read whole pagemap and record each new V2P in separate space because we thought that reading pagemap for each memory access might cause excessive performance overhead.
The pagemap holds all V2P mapping information for the process. However, the V2P mapping may change with time during process execution. Therefore, in order to find the correct V2P mapping for all memory accesses, it is necessary to read a new pagemap for each access and search for the physical frame number corresponding to the Virtual page number. If the overhead of reading pagemap frequently is not a problem for you, V2P mapping information can be obtained using pagemap without the  kernel module.

2. The reason why we used Valgrind is that Valgrind already had a built-in feature to deliver the load/store instructions of the process to the internal CPU cache simulator. Since the purpose of this trace generator is to obtain memory requests after they are absorbed by CPU cache, it records the memory addresses caused by LLC misses and write-backs of the CPU cache simulator rather than raw load/store instructions in the process.
The concept of this tool is not particularly limited to Valgrind. Since Intel Pin tool can obtain accurate raw load/store instructions for the process, the same feature can be implemented by adding a CPU cache simulator within the Pin tool or passing the load/store instructions to a separate CPU cache simulator.

I hope this answer was helpful to you.

**Comment by Michael-J-K94** [comment]
Thank you for the detailed answer! Yes, the answer was very helpful for me and actually cleared out all of my questions regarding this matter. It seems wise to use a separate kernel module and separate space, in terms of the performance overhead.

**Comment by Michael-J-K94** [comment]
Sorry, but a question again;

I think the user process cannot access even its own pagemap, due to the possible Rowhammer exploitation (https://www.kernel.org/doc/Documentation/vm/pagemap.txt). I have also tried it my own, but failed.

I'm curious if you've had success in accessing the pagemap with the user process?

**Comment by arter97** [comment]
> Sorry, but a question again;
> 
> I think the user process cannot access even its own pagemap, due to the possible Rowhammer exploitation (https://www.kernel.org/doc/Documentation/vm/pagemap.txt). I have also tried it my own, but failed.
> 
> I'm curious if you've had success in accessing the pagemap with the user process?

procfs' pagemap is printed in a binary format. You'd need to use a specialized tool to read it properly. One example would be: https://github.com/dwks/pagemap.

As per the documentation you linked yourself, the PFN is only accessible to users with CAP_SYS_ADMIN (which therefore includes root).

Also, please note that our tool doesn't use pagemap from procfs. We've only used it internally during testing.

**Comment by Michael-J-K94** [comment]
Thank you for the detailed answers.

I was aware of the binary format, and used few ways like using lseek() or pread() myself, which did not work. Even the tool you have shared seemed legit, but did not work.

FYI, I'm using a Ubuntu 22.04, and although I doubt that it hardly matters, using a newer SPR machine. I should figure stuff out more by myself.

Still, thank you so much!
